### ISSUE TITLE
[Discussion] Literature References

### ISSUE THREAD

**Issue by mazzma12** [ANSSI-FR/AnoMark#10]
Hi,

I am interested in the method you suggest and wanted to know if you had use of literature paper on the matter, and if you had any to recommend ? 

(Sorry for opening an issue for this, it's more a _discussion_)

**Comment by ajunius-ANSSI** [comment]
Hello,

You can check the references at the end of this paper (written in French but the references are english) that we published some times ago : https://www.sstic.org/media/SSTIC2022/SSTIC-actes/anomark_detection_anomalies_dans_des_lignes_de_com/SSTIC2022-Article-anomark_detection_anomalies_dans_des_lignes_de_commande_chaines_de_markov-junius.pdf

Otherwise you can check papers about Markov Chains and Hidden Markov Chains if you want to dive deeper in the subject.

Have a nice day,
Alexandre
