### ISSUE TITLE
What is a good 'order' value to use?

### ISSUE THREAD

**Issue by cccs-kevin** [ANSSI-FR/AnoMark#3]
Hi @ajunius-ANSSI  et al.

This question obviously depends on the dataset used, but what would a good number to choose for 'order'? The average length of a command line in the dataset? The maximum length of a command line in the dataset? Somewhere in-between?

Thanks,

Kevin 🇨🇦

**Comment by ajunius-ANSSI** [comment]
Hello,

We advise to choose a 4-gram order to train your model. This is empirical, but we can see that it is the mean length of a token, thus you will capture the transition both at a "word" level and inside large blocks (as when base64 encoded).
You cannot choose the length of a command line as the model order, because you will only get one transition. You need to analyze multiple transitions in the string to get a relevant likelihood for the line.

Regards,
Alexandre 🇫🇷

**Comment by cccs-kevin** [comment]
Ah perfect, as you can tell, machine-learning is above me haha. Thank you!
